// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rwmkkxbiqaetilkxiccp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3bWtreGJpcWFldGlsa3hpY2NwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjExNjExMzgsImV4cCI6MjA3NjczNzEzOH0.ZW__BAlB4J9pR3kMZAB6LJJ_3OuB-58mA2xtxx2J5EA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});